// <auto-generated />
using System;
using Bulky.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bulky.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bulky.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Bebidas"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Cervezas"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Licores"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Vinos"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Comidas"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Postres"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Snacks"
                        });
                });

            modelBuilder.Entity("Bulky.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 4, 20, 11, 46, 1, 218, DateTimeKind.Local).AddTicks(9636),
                            LastUpdate = new DateTime(2025, 4, 20, 11, 46, 1, 218, DateTimeKind.Local).AddTicks(9933),
                            Name = "Memo Grillo",
                            Status = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 4, 20, 11, 46, 1, 219, DateTimeKind.Local).AddTicks(210),
                            LastUpdate = new DateTime(2025, 4, 20, 11, 46, 1, 219, DateTimeKind.Local).AddTicks(212),
                            Name = "MESA-01",
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 4, 20, 11, 46, 1, 219, DateTimeKind.Local).AddTicks(214),
                            LastUpdate = new DateTime(2025, 4, 20, 11, 46, 1, 219, DateTimeKind.Local).AddTicks(215),
                            Name = "MESA-02",
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 4, 20, 11, 46, 1, 219, DateTimeKind.Local).AddTicks(216),
                            LastUpdate = new DateTime(2025, 4, 20, 11, 46, 1, 219, DateTimeKind.Local).AddTicks(217),
                            Name = "MESA-03",
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 4, 20, 11, 46, 1, 219, DateTimeKind.Local).AddTicks(218),
                            LastUpdate = new DateTime(2025, 4, 20, 11, 46, 1, 219, DateTimeKind.Local).AddTicks(219),
                            Name = "MESA-04",
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 4, 20, 11, 46, 1, 219, DateTimeKind.Local).AddTicks(220),
                            LastUpdate = new DateTime(2025, 4, 20, 11, 46, 1, 219, DateTimeKind.Local).AddTicks(221),
                            Name = "MESA-05",
                            Status = 0,
                            Type = 2
                        });
                });

            modelBuilder.Entity("Bulky.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubCategory")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            CurrentStock = 100,
                            Name = "COCA-COLA",
                            ReorderLevel = 10,
                            Status = 1,
                            SubCategory = 0,
                            UnitCost = 1.50m,
                            UnitPrice = 2.00m
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            CurrentStock = 100,
                            Name = "GINGER ALE",
                            ReorderLevel = 10,
                            Status = 1,
                            SubCategory = 0,
                            UnitCost = 1.50m,
                            UnitPrice = 2.00m
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            CurrentStock = 100,
                            Name = "SODA",
                            ReorderLevel = 10,
                            Status = 1,
                            SubCategory = 0,
                            UnitCost = 1.50m,
                            UnitPrice = 2.00m
                        },
                        new
                        {
                            Id = 4,
                            Category = 2,
                            CurrentStock = 100,
                            Name = "IMPERIAL REG",
                            ReorderLevel = 10,
                            Status = 1,
                            SubCategory = 0,
                            UnitCost = 1.50m,
                            UnitPrice = 2.00m
                        },
                        new
                        {
                            Id = 5,
                            Category = 2,
                            CurrentStock = 100,
                            Name = "IMPERIAL LIGHT",
                            ReorderLevel = 10,
                            Status = 1,
                            SubCategory = 0,
                            UnitCost = 1.50m,
                            UnitPrice = 2.00m
                        },
                        new
                        {
                            Id = 6,
                            Category = 2,
                            CurrentStock = 100,
                            Name = "IMPERIAL ULTRA",
                            ReorderLevel = 10,
                            Status = 1,
                            SubCategory = 0,
                            UnitCost = 1.50m,
                            UnitPrice = 2.00m
                        });
                });

            modelBuilder.Entity("Bulky.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PIN")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 4, 20, 11, 46, 1, 216, DateTimeKind.Local).AddTicks(9329),
                            LastLogin = new DateTime(2025, 4, 20, 11, 46, 1, 218, DateTimeKind.Local).AddTicks(7101),
                            Name = "Admin",
                            PIN = 1234,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 4, 20, 11, 46, 1, 218, DateTimeKind.Local).AddTicks(7513),
                            LastLogin = new DateTime(2025, 4, 20, 11, 46, 1, 218, DateTimeKind.Local).AddTicks(7516),
                            Name = "User",
                            PIN = 5678,
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
