// <auto-generated />
using System;
using BulkyWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulkyWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BulkyWeb.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Bebidas"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Cervezas"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Licores"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Vinos"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Comidas"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Postres"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Snacks"
                        });
                });

            modelBuilder.Entity("BulkyWeb.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubCategory")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            CurrentStock = 100,
                            Name = "COCA-COLA",
                            ReorderLevel = 10,
                            Status = 1,
                            SubCategory = 0,
                            UnitCost = 1.50m,
                            UnitPrice = 2.00m
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            CurrentStock = 100,
                            Name = "GINGER ALE",
                            ReorderLevel = 10,
                            Status = 1,
                            SubCategory = 0,
                            UnitCost = 1.50m,
                            UnitPrice = 2.00m
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            CurrentStock = 100,
                            Name = "SODA",
                            ReorderLevel = 10,
                            Status = 1,
                            SubCategory = 0,
                            UnitCost = 1.50m,
                            UnitPrice = 2.00m
                        },
                        new
                        {
                            Id = 4,
                            Category = 2,
                            CurrentStock = 100,
                            Name = "IMPERIAL REG",
                            ReorderLevel = 10,
                            Status = 1,
                            SubCategory = 0,
                            UnitCost = 1.50m,
                            UnitPrice = 2.00m
                        },
                        new
                        {
                            Id = 5,
                            Category = 2,
                            CurrentStock = 100,
                            Name = "IMPERIAL LIGHT",
                            ReorderLevel = 10,
                            Status = 1,
                            SubCategory = 0,
                            UnitCost = 1.50m,
                            UnitPrice = 2.00m
                        },
                        new
                        {
                            Id = 6,
                            Category = 2,
                            CurrentStock = 100,
                            Name = "IMPERIAL ULTRA",
                            ReorderLevel = 10,
                            Status = 1,
                            SubCategory = 0,
                            UnitCost = 1.50m,
                            UnitPrice = 2.00m
                        });
                });

            modelBuilder.Entity("BulkyWeb.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PIN")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 4, 17, 18, 43, 46, 464, DateTimeKind.Local).AddTicks(4873),
                            LastLogin = new DateTime(2025, 4, 17, 18, 43, 46, 466, DateTimeKind.Local).AddTicks(2766),
                            Name = "Admin",
                            PIN = 1234,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 4, 17, 18, 43, 46, 466, DateTimeKind.Local).AddTicks(3249),
                            LastLogin = new DateTime(2025, 4, 17, 18, 43, 46, 466, DateTimeKind.Local).AddTicks(3252),
                            Name = "User",
                            PIN = 5678,
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
